id: P24B2B44D
initial_creation_type: input
source_metadata:
  Title: Manuscripts Remains of Buddhist literature found in Eastern Turkestan
  Editor: Hoernle, A.F.Rudolf
  Publisher: Sri Satguru Publications
  Place of Publication: Delhi
  Year: '1988'
  Aparimitāyuḥ nāma mahāyāna sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:58:22.584638'
last_modified_at: '2022-03-08T15:58:22.584646'
